on:
  push:
  workflow_dispatch:

name: CI

env:
  CARGO_NET_RETRY: 3
  CARGO_HTTP_CHECK_REVOKE: false

jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest, ubuntu-latest]
        foo: [1,2,3,4]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # - run: rustup set auto-self-update disable
      #   if: contains(runner.os, 'windows')
      #   shell: bash
      - name: Install Rust toolchain ${{ matrix.foo }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal